name: ecfinal
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - statsmodels
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - ipykernel
  - pip
  - pip:
    - stargazer
